import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  ThemeProvider,
  ToastProvider,
  SocketProvider,
  ModalProvider,
} from "@/components/providers";
import { ClerkProvider } from "@clerk/nextjs";
import { cn } from "@/lib";
import QueryProvider from "@/components/providers/query-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ai Knowledge Verse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "min-h-screen antialiased")}>
         <QueryProvider>

        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
          storageKey="ai-knowledge-theme"
        >
          <ClerkProvider>
            <SocketProvider>
              <ToastProvider />
              <ModalProvider />
              {children}
            </SocketProvider>
          </ClerkProvider>
        </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
